module.exports = function(grunt) {
    'use strict';

    var fs = require('fs'),
        path = require('path');

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        jshint: {
            all: {
                src: [
                    'conkitty.js',
                    'parser.js',
                    'generator.js',
                    'types.js',
                    'errors.js',
                    'utils.js',
                    'browser.js',
                    'bin/conkitty',
                    'Gruntfile.js'
                ],
                options: {
                    jshintrc: '.jshintrc'
                }
            }
        },

        clean: {
            tmp: ['tmp'],
            'browser.js': ['browser.js']
        },

        conkitty: {
            test: {
                files: {
                    'tmp/test.ctpl.js': [
                        'test/basic.ctpl',
                        'test/selectors.ctpl',
                        'test/nodes.ctpl'
                    ]
                }
            }
        },

        uglify: {
            options: {
                preserveComments: 'some'
            },
            build: {
                files: {
                    'tmp/test.ctpl.min.js': 'tmp/test.ctpl.js'
                }
            }
        },

        qunit: {
            all: ['test/**/*.html']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-qunit');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-clean');

    grunt.registerMultiTask('conkitty', function() {
        var Conkitty = require(__dirname + '/conkitty.js'),
            conkitty;

        this.files.forEach(function(f) {
            conkitty = new Conkitty();

            f.src.map(function(filename) {
                conkitty.push(grunt.file.read(filename), path.resolve(path.dirname(filename)));
            });

            conkitty.generate();

            grunt.file.write(f.dest, conkitty.getTemplatesCode());
            grunt.log.writeln('File "' + f.dest + '" created.');
        });
    });

    grunt.registerTask('browser.js', function() {
        var browser = fs.readFileSync(__dirname + '/_browser.js', {encoding: 'utf8'}),
            common = fs.readFileSync(__dirname + '/_common.js', {encoding: 'utf8'});

        common = common.replace(/\n(?!\n|$)/g, '\n    ');
        browser = browser.replace('/*** common.js inserted here ***/', common);

        fs.writeFileSync(__dirname + '/browser.js', '/* This file is automatically generated from _browser.js and _common.js */\n\n' + browser);
        grunt.log.writeln('File "browser.js" created.');
    });

    grunt.registerTask('default', ['jshint', 'clean', 'browser.js', 'conkitty', 'uglify', 'qunit']);
};
